name: Terraform Brownfield Deployment

on:
  push:
    branches:
      - feature-Brownfield-project

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform Deployment
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environment/prod

    steps:

      # Checkout Code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Azure Authentication using OIDC / WIF
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3

      # Terraform Format
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # Terraform Init
      - name: Terraform Init
        run: terraform init

      # Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"

      # Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="terraform.tfvars"